# Generated by Django 5.1.4 on 2025-03-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='license',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
