# Generated by Django 5.1.4 on 2025-03-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, choices=[('Neurologist', 'Neurologist'), ('Psychiatrist', 'Psychiatrist'), ('Primary Care Physician', 'Primary Care Physician'), ('Sleep Specialist', 'Sleep Specialist')], default=None, max_length=50, null=True),
        ),
    ]
