# Generated by Django 5.1.4 on 2025-03-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_doctor_created_on_alter_patient_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(default='images/default.jpg', upload_to='doctor_profiles/'),
        ),
    ]
