# Generated by Django 5.1.4 on 2025-03-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_doctor_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/default.jpg', null=True, upload_to='doctor_profiles/'),
        ),
    ]
