# Generated by Django 5.1.4 on 2025-03-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Patient Registered', 'Patient Registered'), ('Doctor Registered', 'Doctor Registered'), ('Appointment Created', 'Appointment Created'), ('Appointment Updated', 'Appointment Updated'), ('Diagnosis Made', 'Diagnosis Made'), ('Prediction Made', 'Prediction Made')], max_length=50)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
