# Generated by Django 5.1.4 on 2025-03-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='log',
            name='user_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
