# Generated by Django 5.1.6 on 2025-03-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_appointment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='message',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
