# Generated by Django 5.1.6 on 2025-03-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_appointment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
