# Generated by Django 5.1.4 on 2025-03-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_diagnosis_diagnosis_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_date',
            field=models.DateField(default='2025-03-08'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescribed_on',
            field=models.DateField(default='2025-03-08'),
        ),
    ]
