# Generated by Django 5.1.4 on 2025-03-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_alter_diagnosis_diagnosis_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='prescribed_on',
        ),
    ]
