# Generated by Django 5.1.6 on 2025-05-04 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0010_prediction"),
        ("users", "0013_alter_doctor_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hospital", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=150)),
                ("start_year", models.PositiveIntegerField()),
                ("end_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="users.doctor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=150)),
                ("institution", models.CharField(max_length=255)),
                ("year_of_completion", models.PositiveIntegerField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="users.doctor",
                    ),
                ),
            ],
        ),
    ]
