# Generated by Django 5.1.6 on 2025-05-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0011_doctorexperience_doctorqualification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="confidence_score",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
